# Generated by Django 3.2.16 on 2024-10-24 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_ticket', models.CharField(blank=True, max_length=255, null=True)),
                ('type_message', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('msg_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('Routing_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('Peer_in', models.CharField(blank=True, max_length=255, null=True)),
                ('Peer_out', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('calling_party', models.CharField(blank=True, max_length=255, null=True)),
                ('called_party', models.CharField(blank=True, max_length=255, null=True)),
                ('oa', models.CharField(blank=True, max_length=255, null=True)),
                ('da', models.CharField(blank=True, max_length=255, null=True)),
                ('IMSI', models.CharField(blank=True, max_length=255, null=True)),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OaStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oa_number', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
